// This file is AUTO-GENERATED by scripts/generate-translations-index.cjs. Do not edit manually.
// To update, run: npm run generate:translations or pnpm generate:translations

export { adminTranslations } from "./admin";
export { anonymousTranslations } from "./anonymous";
export { genericOauthTranslations } from "./generic-oauth";
